### ISSUE TITLE
PurpleRoom example error during Build Asset Bundles

### ISSUE THREAD

**Issue by EdwardStonePro** [IllusionMods/KoikatsuModdingTools#2]
Hello !

When I tried to build asset bundles with the PurpleRoom example project, it works perfectly until a prompt appears saying "Moving file failed".
"Moving Temp/unitystream.unity3d to C:/Illusion/KoikatsuModdingTools/Build/abdata/map/scene/purpleroom.unity3d:The system cannot find the file specified."
Am I doing something or is it a bug ?
I've the project in the Mods folder as specified, but I may have done something wrong.

Thanks !

**Comment by asp1re7** [comment]
I am having the same issue. @LordMakai  did you managed to fix it? If yes could you please share it with us?

**Comment by ghost** [comment]
> 
> 
> Hello !
> 
> When I tried to build asset bundles with the PurpleRoom example project, it works perfectly until a prompt appears saying "Moving file failed". "Moving Temp/unitystream.unity3d to C:/Illusion/KoikatsuModdingTools/Build/abdata/map/scene/purpleroom.unity3d:The system cannot find the file specified." Am I doing something or is it a bug ? I've the project in the Mods folder as specified, but I may have done something wrong.
> 
> Thanks !

I am having the same issue. @LordMakai  did you manage to fix it? If yes could you please be so kind to share your solution with us?

**Comment by ManlyMarco** [comment]
@asp1re7 Try asking in #mod-modelling channel on the discord server.
